# Generated by Django 5.1.4 on 2025-01-25 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='emailed_job_alerts',
            field=models.BooleanField(default=False),
        ),
    ]
