# Generated by Django 5.1.4 on 2024-12-31 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('link', models.URLField()),
                ('company', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('date_posted', models.DateField(blank=True, null=True)),
                ('job_details', models.TextField(max_length=500)),
            ],
            options={
                'unique_together': {('title', 'company', 'link')},
            },
        ),
    ]
