# Generated by Django 5.1.4 on 2025-01-11 18:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobApi', '0003_alter_preference_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='preference',
            old_name='User',
            new_name='user',
        ),
        migrations.AddField(
            model_name='job',
            name='created_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='description',
            field=models.TextField(default=2013, max_length=1000),
            preserve_default=False,
        ),
    ]
