# Generated by Django 5.1.4 on 2025-01-12 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobApi', '0003_alter_job_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='link',
            field=models.URLField(max_length=300),
        ),
    ]
