# Generated by Django 5.1.4 on 2025-01-23 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobApi', '0004_alter_job_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preference',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='preference',
            name='job_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
