# Generated by Django 5.1.4 on 2025-01-11 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobApi', '0004_rename_user_preference_user_job_created_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
