# Generated by Django 5.1.4 on 2025-01-25 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JobApi', '0005_alter_preference_city_alter_preference_job_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Preference',
        ),
    ]
